# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Users/MicroSnail/Documents/Cornell/Vengalattore/FPGA_PID/rp_memory_test/rp_memory_test.cache/wt [current_project]
set_property parent.project_path D:/Users/MicroSnail/Documents/Cornell/Vengalattore/FPGA_PID/rp_memory_test/rp_memory_test.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files D:/Users/MicroSnail/Documents/Cornell/Vengalattore/FPGA_PID/rp_memory_test/rp_memory_test.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all d:/Users/MicroSnail/Documents/Cornell/Vengalattore/FPGA_PID/rp_memory_test/rp_memory_test.srcs/sources_1/bd/system/ip/system_axi_protocol_converter_0_0/system_axi_protocol_converter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Users/MicroSnail/Documents/Cornell/Vengalattore/FPGA_PID/rp_memory_test/rp_memory_test.srcs/sources_1/bd/system/ip/system_proc_sys_reset_0/system_proc_sys_reset_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Users/MicroSnail/Documents/Cornell/Vengalattore/FPGA_PID/rp_memory_test/rp_memory_test.srcs/sources_1/bd/system/ip/system_proc_sys_reset_0/system_proc_sys_reset_0.xdc]
set_property used_in_implementation false [get_files -all d:/Users/MicroSnail/Documents/Cornell/Vengalattore/FPGA_PID/rp_memory_test/rp_memory_test.srcs/sources_1/bd/system/ip/system_proc_sys_reset_0/system_proc_sys_reset_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Users/MicroSnail/Documents/Cornell/Vengalattore/FPGA_PID/rp_memory_test/rp_memory_test.srcs/sources_1/bd/system/ip/system_processing_system7_0/system_processing_system7_0.xdc]
set_property used_in_implementation false [get_files -all d:/Users/MicroSnail/Documents/Cornell/Vengalattore/FPGA_PID/rp_memory_test/rp_memory_test.srcs/sources_1/bd/system/ip/system_xadc_0/system_xadc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Users/MicroSnail/Documents/Cornell/Vengalattore/FPGA_PID/rp_memory_test/rp_memory_test.srcs/sources_1/bd/system/ip/system_xadc_0/system_xadc_0.xdc]
set_property used_in_implementation false [get_files -all D:/Users/MicroSnail/Documents/Cornell/Vengalattore/FPGA_PID/rp_memory_test/rp_memory_test.srcs/sources_1/bd/system/system_ooc.xdc]
set_property is_locked true [get_files D:/Users/MicroSnail/Documents/Cornell/Vengalattore/FPGA_PID/rp_memory_test/rp_memory_test.srcs/sources_1/bd/system/system.bd]

read_verilog -library xil_defaultlib -sv {
  D:/Users/MicroSnail/Documents/Cornell/Vengalattore/FPGA_PID/rp_memory_test/rp_memory_test.srcs/sources_1/imports/fpga/rtl/interface/sys_bus_if.sv
  D:/Users/MicroSnail/Documents/Cornell/Vengalattore/FPGA_PID/rp_memory_test/rp_memory_test.srcs/sources_1/imports/fpga/rtl/interface/axi4_if.sv
  D:/Users/MicroSnail/Documents/Cornell/Vengalattore/FPGA_PID/rp_memory_test/rp_memory_test.srcs/sources_1/imports/fpga/rtl/axi4_slave.sv
  D:/Users/MicroSnail/Documents/Cornell/Vengalattore/FPGA_PID/rp_memory_test/rp_memory_test.srcs/sources_1/imports/fpga/rtl/red_pitaya_pll.sv
  D:/Users/MicroSnail/Documents/Cornell/Vengalattore/FPGA_PID/rp_memory_test/rp_memory_test.srcs/sources_1/imports/fpga/prj/classic/rtl/red_pitaya_ps.sv
  D:/Users/MicroSnail/Documents/Cornell/Vengalattore/FPGA_PID/rp_memory_test/rp_memory_test.srcs/sources_1/imports/fpga/prj/classic/rtl/red_pitaya_pwm.sv
  D:/Users/MicroSnail/Documents/Cornell/Vengalattore/FPGA_PID/rp_memory_test/rp_memory_test.srcs/sources_1/imports/fpga/prj/classic/rtl/red_pitaya_top.sv
}
read_verilog -library xil_defaultlib {
  D:/Users/MicroSnail/Documents/Cornell/Vengalattore/FPGA_PID/rp_memory_test/rp_memory_test.srcs/sources_1/bd/system/hdl/system_wrapper.v
  D:/Users/MicroSnail/Documents/Cornell/Vengalattore/FPGA_PID/rp_memory_test/rp_memory_test.srcs/sources_1/imports/fpga/prj/classic/rtl/red_pitaya_dfilt1.v
  D:/Users/MicroSnail/Documents/Cornell/Vengalattore/FPGA_PID/rp_memory_test/rp_memory_test.srcs/sources_1/imports/fpga/prj/classic/rtl/axi_wr_fifo.v
  D:/Users/MicroSnail/Documents/Cornell/Vengalattore/FPGA_PID/rp_memory_test/rp_memory_test.srcs/sources_1/imports/fpga/prj/classic/rtl/axi_master.v
  D:/Users/MicroSnail/Documents/Cornell/Vengalattore/FPGA_PID/rp_memory_test/rp_memory_test.srcs/sources_1/imports/fpga/prj/classic/rtl/red_pitaya_pid_block.v
  D:/Users/MicroSnail/Documents/Cornell/Vengalattore/FPGA_PID/rp_memory_test/rp_memory_test.srcs/sources_1/imports/fpga/prj/classic/rtl/red_pitaya_ams.v
  D:/Users/MicroSnail/Documents/Cornell/Vengalattore/FPGA_PID/rp_memory_test/rp_memory_test.srcs/sources_1/imports/fpga/prj/classic/rtl/red_pitaya_scope.v
  D:/Users/MicroSnail/Documents/Cornell/Vengalattore/FPGA_PID/rp_memory_test/rp_memory_test.srcs/sources_1/imports/fpga/prj/classic/rtl/red_pitaya_hk.v
  D:/Users/MicroSnail/Documents/Cornell/Vengalattore/FPGA_PID/rp_memory_test/rp_memory_test.srcs/sources_1/imports/fpga/prj/classic/rtl/red_pitaya_pid.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Users/MicroSnail/Documents/Cornell/Vengalattore/FPGA_PID/rp_memory_test/rp_memory_test.srcs/constrs_1/imports/sdc/red_pitaya.xdc
set_property used_in_implementation false [get_files D:/Users/MicroSnail/Documents/Cornell/Vengalattore/FPGA_PID/rp_memory_test/rp_memory_test.srcs/constrs_1/imports/sdc/red_pitaya.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top red_pitaya_top -part xc7z010clg400-1


write_checkpoint -force -noxdef red_pitaya_top.dcp

catch { report_utilization -file red_pitaya_top_utilization_synth.rpt -pb red_pitaya_top_utilization_synth.pb }
